import "./globals.css";

export const metadata = {
	title: "Lowe's App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="background-[#F8FAFC flex items-center justify-center">
				{children}
			</body>
		</html>
	);
}
